### ISSUE TITLE
How to add mobile input  ? for android device

### ISSUE THREAD

**Issue by stickylabdev** [bunashibu/kikan#1]
I tried it myself but it was difficult

**Comment by stickylabdev** [comment]
i can edit it ,yeah

**Comment by stickylabdev** [comment]
no istill cant edit it , ifindi it just in demoproject ,so it not yet solved bro

**Comment by stickylabdev** [comment]
i can only edit the left right and jump movement but icant edit the skills yet ,its hard ,can you help me please 🍡 https://paste.pics/d0453bc050db1329e0286c477aa22951

**Comment by SiunCyclone** [comment]
Wow, I didn't think about mobile support. but thank you for trying to implementation.
The skills are instantiated by input in here(https://github.com/bunashibu/kikan/blob/master/Assets/Scripts/Weapon/SkillInstantiator.cs#L33)
and the key input setting is here(https://github.com/bunashibu/kikan/blob/master/Assets/Scripts/Weapon/Weapon.cs#L40)🍡

**Comment by stickylabdev** [comment]
sure and cool ,, ican do it ,, but just need time to tweak it more ,,,,

**Comment by stickylabdev** [comment]
thanks for the reply and wwooooooooooooooow ,, you've replied my message , i appreciate it so much 
and ,,There is something I want to ask, that if I can edit all the image assets, then I upload them to the PlayStore, I hope I'm allowed : '( https://snag.gy/cJr289.jpg

**Comment by stickylabdev** [comment]
maybe i have to put this messsage on the game splash screen  ? " Copyright (c) 2016 bunashibu "  🗡

**Comment by SiunCyclone** [comment]
That's cool! I don't mind if you upload it to the PlayStore with copyright notice🗡

**Comment by stickylabdev** [comment]
ok thanks a lot 🥇
