### ISSUE TITLE
i still learning about team battle , i read your code , and

### ISSUE THREAD

**Issue by stickylabdev** [bunashibu/kikan#2]
i still learning , its hard :D ,, i want to implement team battle to my game , can you help me learn about it if you dont mind

**Comment by SiunCyclone** [comment]
I think team battle is already implemented. If you couldn't play team battle on your unity editor, you might not set an AppId on your PhotonServerSettings.
![photon1](https://user-images.githubusercontent.com/2681430/56815950-7da9ee00-687d-11e9-97e1-ccd61fbcb200.png)
![photon2](https://user-images.githubusercontent.com/2681430/56815958-839fcf00-687d-11e9-87a4-b14950fa9105.png)
Or, if you are trying to play on Android, I don't know whether photon is compatible with mobile support.

**Comment by stickylabdev** [comment]
this is not what i mean -_- ,,I have made battle royale simple games, look at this https://play.google.com/store/apps/details?id=com.stickylab.FightAllAnimeChars&hl=en , but I am still in the process of making a team battle

**Comment by SiunCyclone** [comment]
In my game,
1. Set team custom properties to the player before start battle(https://github.com/bunashibu/kikan/blob/master/Assets/Scripts/Matching/BattleLauncher.cs#L78-L79)
2. When player is instantiated in battle scene, team is read from custom properties(https://github.com/bunashibu/kikan/blob/master/Assets/Scripts/Player/PlayerInfo.cs#L10)
3. All skill decide whether player is one's teammate or enemy by TeamChecker(https://github.com/bunashibu/kikan/blob/master/Assets/Scripts/Skill/Magician/MagicianShift.cs#L20)
(https://github.com/bunashibu/kikan/blob/master/Assets/Scripts/Skill/Utility/TeamChecker.cs)

**Comment by stickylabdev** [comment]
yeah thanks a lot bro ,,i appreciate your feedback

**Comment by SiunCyclone** [comment]
no problem
