### ISSUE TITLE
something touble when i add input ui 

### ISSUE THREAD

**Issue by stickylabdev** [bunashibu/kikan#4]
I used a simple input plugin to make it controllable via UI, but there was something strange when I used warrior, the left control and space buttons didn't work properly, even though when I used another role, everything went smoothly: '(, can you can you help me?

i use simpleinput plugin

**Comment by SiunCyclone** [comment]
I don't know about the simple input plugin, but warrior left control and space button are implemented in (https://github.com/bunashibu/kikan/blob/master/Assets/Scripts/Weapon/Unique/Hammer.cs) so you may check these.
Also, Panda left control is similar implementation to them so it might doesn't work properly in your environment.(https://github.com/bunashibu/kikan/blob/master/Assets/Scripts/Weapon/Unique/Fist.cs)

**Comment by stickylabdev** [comment]
thank you so much ,its fixed
